
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { BookOpen, Edit3, Brain, UserCircle, Settings as SettingsIcon } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';

export default function DashboardPage() {
  return (
    <div className="container mx-auto py-8">
      <div className="mb-8 text-center">
        <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
          Welcome to your <span className="text-primary">ADDISSPARK</span> Dashboard
        </h1>
        <p className="mt-2 text-lg text-muted-foreground">
          Here you can manage your learning, track progress, and access all features.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        <Card className="shadow-lg hover:shadow-xl transition-shadow duration-300">
          <CardHeader>
            <div className="flex items-center gap-4">
              <BookOpen className="h-10 w-10 text-primary" />
              <CardTitle className="text-2xl">Study Resources</CardTitle>
            </div>
            <CardDescription>
              Access curated notes, video lectures, and other materials.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Image 
              src="https://placehold.co/600x400.png" 
              alt="Study Resources" 
              width={600} 
              height={400} 
              className="rounded-md mb-4"
              data-ai-hint="books library" 
            />
            <Button asChild className="w-full">
              <Link href="/dashboard/resources">Explore Resources</Link>
            </Button>
          </CardContent>
        </Card>

        <Card className="shadow-lg hover:shadow-xl transition-shadow duration-300">
          <CardHeader>
            <div className="flex items-center gap-4">
              <Edit3 className="h-10 w-10 text-primary" />
              <CardTitle className="text-2xl">Practice Exams</CardTitle>
            </div>
            <CardDescription>
              Test your knowledge with realistic exam simulations.
            </CardDescription>
          </CardHeader>
          <CardContent>
             <Image 
              src="https://placehold.co/600x400.png" 
              alt="Practice Exams" 
              width={600} 
              height={400} 
              className="rounded-md mb-4"
              data-ai-hint="test exam"
            />
            <Button asChild className="w-full">
              <Link href="/dashboard/exams">Take an Exam</Link>
            </Button>
          </CardContent>
        </Card>

        <Card className="shadow-lg hover:shadow-xl transition-shadow duration-300">
          <CardHeader>
            <div className="flex items-center gap-4">
              <Brain className="h-10 w-10 text-primary" />
              <CardTitle className="text-2xl">AI Study Plan</CardTitle>
            </div>
            <CardDescription>
              Get a personalized study plan generated by AI.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Image 
              src="https://placehold.co/600x400.png" 
              alt="AI Study Plan" 
              width={600} 
              height={400} 
              className="rounded-md mb-4"
              data-ai-hint="ai schedule"
            />
            <Button asChild className="w-full">
              <Link href="/dashboard/study-plan">Generate Plan</Link>
            </Button>
          </CardContent>
        </Card>

        <Card className="shadow-lg hover:shadow-xl transition-shadow duration-300 md:col-span-1 lg:col-span-1">
           <CardHeader>
            <div className="flex items-center gap-4">
              <UserCircle className="h-10 w-10 text-primary" />
              <CardTitle className="text-2xl">Profile</CardTitle>
            </div>
            <CardDescription>
              View and manage your account details.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Image 
              src="https://placehold.co/600x400.png" 
              alt="Profile" 
              width={600} 
              height={400} 
              className="rounded-md mb-4"
              data-ai-hint="user avatar"
            />
            <Button asChild className="w-full">
              <Link href="/dashboard/profile">View Profile</Link>
            </Button>
          </CardContent>
        </Card>
        
        <Card className="shadow-lg hover:shadow-xl transition-shadow duration-300 md:col-span-1 lg:col-span-2">
           <CardHeader>
            <div className="flex items-center gap-4">
              <SettingsIcon className="h-10 w-10 text-primary" />
              <CardTitle className="text-2xl">Settings</CardTitle>
            </div>
            <CardDescription>
              Configure your application preferences and settings.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Image 
              src="https://placehold.co/600x400.png" 
              alt="Settings" 
              width={600} 
              height={400} 
              className="rounded-md mb-4"
              data-ai-hint="gears settings"
            />
            <Button asChild className="w-full">
              <Link href="/dashboard/settings">Go to Settings</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
